export const baseData = state => state.baseData
export const goods = state => state.goods
export const myintegral = state => state.myintegral
export const userid = state => state.userid
export const token = state => state.token
export const praiseList = state => state.praiseList
export const username = state => state.username
export const password = state => state.password
export const shareDetail = state => state.shareDetail
